export const FETCH_CONVERSATIONS = 'FETCH_CONVERSATIONS';
export const FETCH_CONVERSATION_MESSAGES = 'FETCH_CONVERSATION_MESSAGES';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const FETCH_MESSAGE_PAIRS = 'FETCH_MESSAGE_PAIRS';
export const ADD_MESSAGE_PAIR = 'ADD_MESSAGE_PAIR';
